# Generated by Django 4.2.4 on 2023-08-22 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_order_date_alter_order_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes'),
        ),
    ]
