# Generated by Django 4.2.4 on 2023-08-25 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_order_qrcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='signature',
            new_name='ecommerce_id',
        ),
    ]
