# Generated by Django 4.2.4 on 2023-08-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_signature_order_ecommerce_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ecommerce_id',
            field=models.CharField(max_length=100),
        ),
    ]
