# Generated by Django 4.2.4 on 2023-08-25 11:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_order_ecommerce_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='delivery_status',
        ),
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='ecommerce_id',
            field=models.CharField(default=uuid.UUID('12f62c58-d138-4605-ae07-182671f7f38b'), max_length=100),
        ),
    ]
