# Generated by Django 4.2.4 on 2023-08-25 11:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_status_order_delivery_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ecommerce_id',
            field=models.CharField(default=uuid.UUID('e0cc5e62-16f5-4c51-bbe0-ba11c7ae2ad8'), max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.BooleanField(blank=True),
        ),
    ]
