# Generated by Django 4.2.4 on 2023-08-26 11:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_cart_shipping_alter_cart_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(limit_value=models.DateField(blank=True, null=True))]),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('Shipping', 'Shipping'), ('Cancelled', 'Cancelled'), ('Out for Delivery', 'Out for Delivery')], default='Pending', max_length=20),
        ),
    ]
