# Generated by Django 4.2.5 on 2023-09-15 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_order_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
