# Generated by Django 4.2.5 on 2023-09-15 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_delete_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='code',
        ),
    ]
